services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: space_center
      POSTGRES_USER: space_user
      POSTGRES_PASSWORD: space_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U space_user -d space_center"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - space-net

  kafka:
    image: bitnamilegacy/kafka:3.9
    container_name: kafka
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "29092:29092"
    networks:
      - space-net

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: space-operation-server:v1.0.0
    container_name: server
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/space_center
      SPRING_DATASOURCE_USERNAME: space_user
      SPRING_DATASOURCE_PASSWORD: space_password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      TELEMETRY_GRPC_ADDRESS: static://telemetry-service:9091
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      telemetry-service:
        condition: service_started
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/api/overview || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - space-net

  telemetry-service:
    build:
      context: ./telemetry-service
      dockerfile: Dockerfile
    image: telemetry-service:v1.0.0
    container_name: telemetry-service
    environment:
      SERVER_PORT: 8082
      GRPC_SERVER_PORT: 9091
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_started
    ports:
      - "9091:9091"
    networks:
      - space-net

  mission-service:
    build:
      context: ./mission-scheduler
      dockerfile: Dockerfile
    image: mission-scheduler:v1.0.0
    container_name: mission-service
    depends_on:
      server:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
      SERVER_URL: http://server:8080/api
    ports:
      - "8081:8081"
    networks:
      - space-net

networks:
  space-net:
    driver: bridge
